name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: DoSomething
      run: |
        sudo apt-get -y install ostree
        mkdir -p rootfs myrepo temp

        docker pull debian:testing
        docker save debian:testing --output debian.tar
        tar xf debian.tar -C temp
        cat temp/manifest.json

        tar xf temp/$(jq '.[0].Layers[0]' manifest.json) -C rootfs
        
        cd rootfs
        ostree init --repo ../myrepo

        echo abc > hello.txt
        ostree commit --repo ../myrepo --branch main
        
        sudo tar czf myrepo.tgz myrepo/
        sudo chown runner myrepo.tgz
        
    - run: tree rootfs
    
    - uses: actions/upload-artifact@v3
      with:
        name: ostree-repo
        path: myrepo.tgz
