name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: DoSomething
      run: |
        sudo apt-get -y install ostree
        mkdir -p rootfs myrepo

        docker pull debian:testing
        docker save debian:testing --output debian.tar
        tar xf debian.tar -C rootfs
        
        cd rootfs
        ostree init --repo ../myrepo

        echo abc > hello.txt
        ostree commit --repo ../myrepo --branch main
        
    - run: tree rootfs
    
    - uses: actions/upload-artifact@v3
      with:
        name: ostree-repo
        path: myrepo/
